services:
  jenkins-blueocean:
    image: myjenkins-blueocean:v3
    container_name: jenkins-blueocean
    restart: on-failure
    environment:
      DOCKER_HOST: "unix:///var/run/docker.sock"  # Use Docker socket for communication
    user: ":1001"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    networks:
      - jenkins
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins-data:

networks:
  jenkins:
